# These are supported funding model platforms

github: nanostudios
ko_fi: nanoteslodeejay
buy_me_a_coffee: nanostudios
custom:
  - https://www.ko-fi.com/nanoteslodeejay
  - https://buymeacoffee.com/nanostudios
# Crypto Donations
# Solana (SOL): 8G7jSBjYAPkx2k3mLmsDT4mJEVf2zu1eHucibiRqunCf
# Bitcoin (BTC): bc1qqjshrnhzff4dzy7vc3wwm4pan93qumjxmtqq39
# Ethereum (ETH): 0x68383d5E1ae2f15eb49d1b4A3606bf16538fb563
