apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: uranus-spins
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: your_key
  AWS_SECRET_ACCESS_KEY: your_secret
  AWS_DEFAULT_REGION: us-east-1
