apiVersion: v1
kind: Namespace
metadata:
  name: uranus-spins
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-default
  namespace: uranus-spins
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
